[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
via-ir = true
# remappings = [
#     "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
#     "@openzeppelin/contracts=lib/openzeppelin-contracts/",
# ]

is-system = true

optimizer = true
optimizer_runs = 200

# remappings = ["@eth-infinitism/contracts/=lib/account-abstraction/contracts/","@openzeppelin/contracts=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
